{{- range $key,$val := .Values.applications }}
{{- if $val.enabled | default true}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{- if $val.destination }}
    namespace: {{ $val.destination.namespace | default $.Values.default.app.destination.namespace }}
    server: {{ $val.destination.server | default $.Values.default.app.destination.server }}
    {{- else if $.Values.default.app.destination }}
    namespace: {{ $.Values.default.app.destination.namespace }}
    server: {{ $.Values.default.app.destination.server }}
    {{- end }}
  project: {{ $.Values.default.app.project }}
  syncPolicy:
  {{- if $val.createNamespace | default $.Values.default.app.createNamespace }}
    syncOptions:
      - CreateNamespace=true
  {{- end}}
  {{- if $val.enableAutoSync | default $.Values.default.app.enableAutoSync }}
  {{- if $val.autoSyncPrune }}
    automated:
      prune: {{ $val.autoSyncPrune  }}
    {{- else }}
    automated: {}
    {{- end }}
{{- end }}
  source:
    path: {{ tpl $val.source.path $ }}
    repoURL: {{ $val.source.repoURL | default $.Values.default.app.source.repoURL | required (printf "No source.repoURL specified for %s" $key ) }}
    targetRevision: {{ $val.source.targetRevision | default $.Values.default.app.source.targetRevision | required (printf "No source.targetRevision specified for %s" $key ) }}
{{- if $val.source.extraSourceFields }}
{{ tpl $val.source.extraSourceFields $ | indent 4 }}
{{- else if $.Values.default.app.source.extraSourceFields }}
{{ tpl $.Values.default.app.source.extraSourceFields $ | indent 4 }}
{{- end }}
{{- if $val.extraFields }}
{{ tpl $val.extraFields $ | indent 2 }}
{{- else if $.Values.default.app.extraFields }}
{{ tpl $.Values.default.app.extraFields $ | indent 2 }}
{{- end }}
{{- end }}
{{- end }}